apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30041
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 30040
  selector:
    app: frontend
  type: NodePort