name: Uda'CityShop [sha tag] - Package with Docker
on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Docker meta
        id: meta-adservice
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/adservice1
          tags: |
            type=sha
      -
        name: Build and push - adservice
        uses: docker/build-push-action@v2
        with:
          context: src/adservice
          file: src/adservice/Dockerfile
          push: true
          tags: ${{ steps.meta-adservice.outputs.tags }}
          labels: ${{ steps.meta-adservice.outputs.labels }}

      -
        name: Docker meta
        id: meta-frontend
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend1
          tags: |
            type=sha

      -
        name: Build and push - frontend
        uses: docker/build-push-action@v2
        with:
          context: src/frontend
          file: src/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

      -
        name: Docker meta
        id: meta-productcatalogservice
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/productcatalogservice1
          tags: |
            type=sha

      -
        name: Build and push - productcatalogservice
        uses: docker/build-push-action@v2
        with:
          context: src/productcatalogservice
          file: src/productcatalogservice/Dockerfile
          push: true
          tags: ${{ steps.meta-productcatalogservice.outputs.tags }}
          labels: ${{ steps.meta-productcatalogservice.outputs.labels }}

      -
        name: Docker meta
        id: meta-currencyservice
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/currencyservice1
          tags: |
            type=sha

      -
        name: Build and push - currencyservice
        uses: docker/build-push-action@v2
        with:
          context: src/currencyservice
          file: src/currencyservice/Dockerfile
          push: true
          tags: ${{ steps.meta-currencyservice.outputs.tags }}
          labels: ${{ steps.meta-currencyservice.outputs.labels }}

